api_platform:
    title: '%site_name%'
    version: '%api_version%'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        csv:      ['text/csv']
        html:     ['text/html']
