easy_admin:
    site_name: '%site_name%'
    design:
        assets:
            favicon: 'build/images/favicon.ico'

    entities:
        Item:
            class: App\Entity\Item
            list:
                sort: ['name', 'ASC']
                fields:
                    - property: name
                      template: name.html.twig
                    - property: shortDescription
                    - property: description
                    - property: categories
                      template: categories.html.twig
            search:
                fields: ['name', 'description.name', 'categories.name']
            show:
                fields:
                    - property: name
                    - property: shortDescription
                    - property: description
                    - property: categories
            form:
                fields:
                    - property: name
                    - property: shortDescription
                    - property: description
                    - property: categories

        ItemDescription:
            class: App\Entity\ItemDescription
            label: 'Description'
            list:
                sort: ['name', 'ASC']
                fields:
                    - property: name
                      template: name.html.twig
                    - property: description
                    - property: items
                      label: 'Related items'
                      template: items.html.twig
            show:
                fields:
                    - property: name
                    - property: description
                    - property: items
                      label: 'Related items'
                      type: embedded_list
            form:
                fields:
                    - property: name
                    - property: description
                      type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'

        ItemCategory:
            class: App\Entity\ItemCategory
            label: 'Category'
            list:
                sort: ['name', 'ASC']
                fields:
                    - property: name
                      template: name.html.twig
                    - property: description
                    - property: icon
                      template: icon.html.twig
                    - property: items
                      label: 'Related items'
                      template: items.html.twig
            show:
                fields:
                    - property: name
                    - property: description
                    - property: icon
                    - property: items
                      label: 'Related items'
                      type: embedded_list
                      type_options:
                          entity: Item
            form:
                fields:
                    - property: name
                    - property: description
                      type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'
                    - property: icon
                      type: choice
                      type_options:
                          choices: '%icon_choices%'
                          expanded: true
                          multiple: false

        User:
            class: App\Entity\User
            list:
                role: ROLE_ADMIN
                fields:
                    - property: email
                    - property: roles
                      template: roles.html.twig
                    - property: enabled
                      type: boolean
            show:
                role: ROLE_ADMIN
                fields:
                    - property: enabled
                    - property: email
                    - property: roles
            delete:
                role: ROLE_ADMIN
            form:
                role: ROLE_ADMIN
                fields:
                    - property: enabled
                    - property: email
                    - property: roles
                      type: choice
                      type_options: &role_type_options
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
                    - property: enabled
            new:
                role: ROLE_ADMIN
                fields:
                    - property: plainPassword
                      label: Password
                      type_options:
                          required: true
                      type: text

easy_admin_extension:
    embedded_list:
        open_new_tab: false
